development:
  adapter: postgresql
  encoding: unicode
  database: me_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: me_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: mysql
  database: portfolio
  username: railapps
  password: 123

